# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: genfix 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "genfix"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Corey Osman"]
  s.date = "2015-05-22"
  s.description = "Gemfix is a small utility that will bring all the types of puppet module dependencies together into a single entity"
  s.email = "corey@logicminds.biz"
  s.executables = ["genfix"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "README.md",
    "VERSION",
    "bin/genfix",
    "genfix.gemspec",
    "lib/genfix.rb",
    "lib/genfix/adapters/fixtures.rb",
    "lib/genfix/adapters/librarian.rb",
    "lib/genfix/dependency_base.rb"
  ]
  s.homepage = "http://github.com/logicminds/genfix"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.4"
  s.summary = "Gemfix is a small utility that will bring all the types of puppet module dependencies together into a single entity"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 2.1.2"])
      s.add_runtime_dependency(%q<librarian-puppet>, [">= 2.1.1"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<trollop>, [">= 2.1.2"])
      s.add_dependency(%q<librarian-puppet>, [">= 2.1.1"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 2.1.2"])
    s.add_dependency(%q<librarian-puppet>, [">= 2.1.1"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

